// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Both Operands Empty ', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Both Operands Empty ', async function() {
    await driver.get("http://localhost:8000//")
    await driver.manage().window().setRect({ width: 918, height: 1079 })
    await driver.findElement(By.css("button:nth-child(1)")).click()
  })
})
